Using GPU 3
Running hyperparameter search...
Traceback (most recent call last):
  File "/home/marcus/programming/structural_binding_affinity_predictions_using_gnn/src/train.py", line 432, in <module>
    main()
  File "/home/marcus/programming/structural_binding_affinity_predictions_using_gnn/src/train.py", line 425, in main
    results = tuner.minimize()
              ^^^^^^^^^^^^^^^^
  File "/home/marcus/miniconda3/envs/gnn/lib/python3.12/site-packages/mango/tuner.py", line 127, in minimize
    return self.run()
           ^^^^^^^^^^
  File "/home/marcus/miniconda3/envs/gnn/lib/python3.12/site-packages/mango/tuner.py", line 114, in run
    self.results = self.runBayesianOptimizer()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcus/miniconda3/envs/gnn/lib/python3.12/site-packages/mango/tuner.py", line 176, in runBayesianOptimizer
    X_list, Y_list = self.run_initial()
                     ^^^^^^^^^^^^^^^^^^
  File "/home/marcus/miniconda3/envs/gnn/lib/python3.12/site-packages/mango/tuner.py", line 154, in run_initial
    X_list, Y_list = self.runUserObjective(X_init)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcus/miniconda3/envs/gnn/lib/python3.12/site-packages/mango/tuner.py", line 342, in runUserObjective
    results = self.objective_function(X_next_PS)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcus/programming/structural_binding_affinity_predictions_using_gnn/src/train.py", line 326, in run_for_parameter_tuning
    train_loader = DataLoader(
                   ^^^^^^^^^^^
  File "/home/marcus/miniconda3/envs/gnn/lib/python3.12/site-packages/torch_geometric/loader/dataloader.py", line 87, in __init__
    super().__init__(
  File "/home/marcus/miniconda3/envs/gnn/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 357, in __init__
    batch_sampler = BatchSampler(sampler, batch_size, drop_last)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcus/miniconda3/envs/gnn/lib/python3.12/site-packages/torch/utils/data/sampler.py", line 268, in __init__
    raise ValueError(f"batch_size should be a positive integer value, but got batch_size={batch_size}")
ValueError: batch_size should be a positive integer value, but got batch_size=[32, 128, 64]
